// ═══════════════════════════════════════════════════════════════════════════
// gamee/js/levels.js  — GENERATED by editor (editor/index.html)
// NEEDITOVAT RUČNĚ — otevři editor a publikuj z něj.
// Pokud tento soubor chybí nebo je prázdný, hra automaticky použije
// LEVELS_FALLBACK z game.js (viz resolveLevels()).
// ═══════════════════════════════════════════════════════════════════════════
window.LEVELS = [
  {
    "key": "frog",
    "label": "žabka",
    "type": "relaxing",
    "imageDifficulty": 1,
    "image": {
      "source": "frog"
    },
    "blocks": [],
    "rocketTargets": [
      0,
      7
    ],
    "garage": {
      "col": 3,
      "carriers": [
        {
          "color": 0
        },
        {
          "color": 7
        },
        {
          "color": 3
        }
      ]
    }
  },
  {
    "key": "starwars",
    "label": "C-3PO",
    "type": "relaxing",
    "imageDifficulty": 1,
    "image": {
      "source": "starwars"
    },
    "blocks": [],
    "rocketTargets": [
      1,
      1
    ],
    "garage": {
      "col": 4,
      "carriers": [
        {
          "color": 5
        },
        {
          "color": 1
        },
        {
          "color": 8
        }
      ]
    }
  },
  {
    "key": "smiley",
    "label": "smajlík",
    "type": "relaxing",
    "imageDifficulty": 1,
    "image": {
      "source": "smiley"
    },
    "blocks": [
      {
        "shape": "rect",
        "x": 14,
        "y": 24,
        "w": 8,
        "h": 3,
        "color": 4,
        "hp": 20
      }
    ],
    "rocketTargets": [
      8,
      7
    ],
    "garage": {
      "col": 3,
      "carriers": [
        {
          "color": 3
        },
        {
          "color": 0
        },
        {
          "color": 4
        }
      ]
    }
  },
  {
    "key": "moon",
    "label": "měsíc",
    "type": "relaxing",
    "imageDifficulty": 1,
    "image": {
      "source": "moon"
    },
    "blocks": [],
    "rocketTargets": [
      8,
      5
    ],
    "garage": {
      "col": 4,
      "carriers": [
        {
          "color": 5
        },
        {
          "color": 2
        },
        {
          "color": 6
        }
      ]
    }
  },
  {
    "key": "mondrian",
    "label": "Mondrian",
    "type": "relaxing",
    "imageDifficulty": 1,
    "image": {
      "source": "mondrian"
    },
    "blocks": [],
    "rocketTargets": null,
    "garage": null
  },
  {
    "key": "new-level-6",
    "label": "Nový level",
    "type": "relaxing",
    "imageDifficulty": 1,
    "image": {
      "source": "smiley"
    },
    "blocks": [
      {
        "kind": "mystery",
        "shape": "rect",
        "x": 14,
        "y": 7,
        "w": 8,
        "h": 12,
        "color": 3,
        "hp": 60
      },
      {
        "kind": "solid",
        "shape": "cross",
        "x": 3,
        "y": 4,
        "w": 11,
        "h": 11,
        "color": 1,
        "hp": 60
      },
      {
        "kind": "solid",
        "shape": "rect",
        "x": 22,
        "y": 7,
        "w": 4,
        "h": 4,
        "color": 4,
        "hp": 10
      }
    ],
    "rocketTargets": [
      1,
      0
    ],
    "garage": null
  },
  {
    "key": "new-level-7",
    "label": "Nový level",
    "type": "medium",
    "imageDifficulty": 1,
    "image": {
      "source": "custom",
      "pixels": [
        [
          1,
          2,
          2,
          2,
          1,
          2,
          3,
          2,
          2,
          1,
          0,
          0,
          1,
          0,
          0,
          2,
          8,
          3,
          8,
          8,
          8,
          8,
          8,
          8,
          8,
          8,
          2,
          2,
          2,
          1,
          1,
          6,
          1,
          1,
          1,
          1
        ],
        [
          3,
          2,
          1,
          1,
          8,
          2,
          2,
          6,
          6,
          8,
          0,
          0,
          0,
          0,
          8,
          1,
          2,
          3,
          8,
          8,
          8,
          2,
          2,
          2,
          2,
          8,
          3,
          8,
          8,
          8,
          2,
          3,
          8,
          2,
          2,
          1
        ],
        [
          8,
          2,
          3,
          0,
          1,
          0,
          2,
          0,
          6,
          2,
          0,
          8,
          2,
          8,
          3,
          8,
          3,
          8,
          1,
          3,
          8,
          2,
          2,
          2,
          3,
          2,
          2,
          2,
          8,
          8,
          8,
          6,
          2,
          6,
          6,
          6
        ],
        [
          1,
          0,
          0,
          8,
          0,
          0,
          0,
          6,
          6,
          3,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          4,
          4,
          4,
          4,
          0,
          3,
          2,
          8,
          2,
          8,
          1,
          8,
          2,
          3,
          2,
          6,
          2,
          1
        ],
        [
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          6,
          2,
          3,
          2,
          0,
          8,
          3,
          8,
          0,
          8,
          4,
          4,
          3,
          3,
          2,
          2,
          2,
          0,
          0,
          8,
          2,
          1,
          1,
          6,
          6,
          8,
          2,
          1,
          1
        ],
        [
          0,
          0,
          1,
          1,
          0,
          3,
          2,
          6,
          6,
          6,
          6,
          6,
          6,
          2,
          2,
          2,
          4,
          4,
          2,
          4,
          4,
          4,
          2,
          2,
          2,
          2,
          6,
          6,
          1,
          8,
          5,
          3,
          3,
          1,
          1,
          2
        ],
        [
          2,
          8,
          0,
          2,
          1,
          0,
          3,
          6,
          6,
          4,
          6,
          6,
          2,
          2,
          4,
          4,
          3,
          3,
          2,
          2,
          6,
          6,
          2,
          2,
          1,
          6,
          2,
          2,
          0,
          5,
          6,
          6,
          3,
          3,
          2,
          2
        ],
        [
          2,
          8,
          0,
          0,
          8,
          1,
          1,
          0,
          6,
          4,
          6,
          6,
          2,
          4,
          3,
          3,
          3,
          3,
          0,
          6,
          4,
          4,
          2,
          6,
          6,
          2,
          2,
          2,
          2,
          0,
          1,
          3,
          2,
          3,
          2,
          2
        ],
        [
          2,
          2,
          8,
          2,
          0,
          5,
          0,
          6,
          1,
          4,
          2,
          2,
          2,
          0,
          3,
          6,
          1,
          1,
          3,
          0,
          0,
          0,
          2,
          2,
          2,
          2,
          1,
          6,
          2,
          0,
          6,
          6,
          8,
          2,
          0,
          2
        ],
        [
          2,
          0,
          8,
          8,
          2,
          0,
          6,
          8,
          6,
          4,
          2,
          2,
          6,
          3,
          4,
          4,
          6,
          4,
          2,
          3,
          0,
          1,
          0,
          4,
          1,
          2,
          6,
          6,
          2,
          2,
          6,
          6,
          6,
          6,
          6,
          6
        ],
        [
          2,
          0,
          8,
          8,
          2,
          3,
          0,
          2,
          2,
          2,
          2,
          3,
          3,
          0,
          0,
          4,
          4,
          6,
          2,
          0,
          3,
          0,
          1,
          0,
          0,
          2,
          2,
          1,
          2,
          2,
          6,
          8,
          8,
          2,
          0,
          3
        ],
        [
          2,
          0,
          8,
          8,
          8,
          2,
          2,
          5,
          1,
          0,
          3,
          3,
          6,
          1,
          2,
          0,
          4,
          4,
          2,
          1,
          3,
          1,
          6,
          6,
          1,
          0,
          2,
          6,
          2,
          6,
          2,
          2,
          2,
          1,
          2,
          2
        ],
        [
          2,
          0,
          8,
          3,
          1,
          2,
          4,
          6,
          6,
          3,
          3,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          6,
          4,
          0,
          3,
          0,
          1,
          1,
          0,
          1,
          2,
          5,
          1,
          1,
          8,
          2,
          2,
          1,
          2
        ],
        [
          2,
          6,
          2,
          1,
          6,
          2,
          2,
          2,
          2,
          3,
          2,
          0,
          6,
          1,
          6,
          1,
          0,
          4,
          4,
          1,
          6,
          3,
          0,
          0,
          1,
          6,
          3,
          2,
          0,
          6,
          1,
          0,
          2,
          2,
          2,
          0
        ],
        [
          6,
          0,
          8,
          1,
          6,
          6,
          0,
          0,
          6,
          3,
          2,
          4,
          6,
          6,
          6,
          1,
          6,
          0,
          4,
          6,
          6,
          4,
          3,
          0,
          0,
          1,
          3,
          2,
          6,
          6,
          1,
          8,
          8,
          2,
          2,
          2
        ],
        [
          2,
          0,
          1,
          2,
          6,
          3,
          0,
          4,
          6,
          3,
          2,
          2,
          6,
          6,
          0,
          1,
          1,
          1,
          0,
          2,
          4,
          4,
          3,
          0,
          0,
          1,
          3,
          6,
          6,
          3,
          1,
          2,
          2,
          1,
          2,
          1
        ],
        [
          2,
          1,
          8,
          2,
          6,
          0,
          0,
          4,
          6,
          6,
          3,
          6,
          2,
          6,
          6,
          6,
          2,
          6,
          1,
          6,
          0,
          3,
          3,
          0,
          0,
          0,
          3,
          4,
          4,
          0,
          3,
          1,
          2,
          2,
          1,
          0
        ],
        [
          1,
          2,
          0,
          6,
          2,
          0,
          2,
          4,
          6,
          4,
          3,
          3,
          2,
          2,
          3,
          3,
          3,
          3,
          6,
          1,
          4,
          3,
          3,
          3,
          3,
          0,
          3,
          4,
          4,
          0,
          0,
          1,
          2,
          2,
          1,
          3
        ],
        [
          1,
          2,
          6,
          6,
          0,
          2,
          0,
          4,
          6,
          4,
          6,
          3,
          3,
          3,
          2,
          1,
          2,
          3,
          3,
          6,
          1,
          3,
          3,
          6,
          2,
          3,
          3,
          3,
          4,
          8,
          0,
          1,
          0,
          2,
          3,
          1
        ],
        [
          1,
          3,
          6,
          8,
          2,
          2,
          4,
          0,
          6,
          4,
          4,
          6,
          3,
          3,
          6,
          1,
          6,
          2,
          3,
          0,
          4,
          3,
          3,
          0,
          0,
          0,
          3,
          3,
          4,
          1,
          8,
          1,
          1,
          8,
          1,
          1
        ],
        [
          2,
          2,
          6,
          1,
          1,
          1,
          4,
          4,
          6,
          4,
          4,
          6,
          6,
          6,
          3,
          6,
          1,
          3,
          3,
          2,
          1,
          1,
          3,
          2,
          6,
          6,
          6,
          6,
          0,
          4,
          2,
          2,
          1,
          3,
          1,
          1
        ],
        [
          2,
          6,
          2,
          8,
          2,
          2,
          4,
          4,
          4,
          4,
          4,
          3,
          1,
          0,
          0,
          3,
          3,
          3,
          1,
          1,
          1,
          2,
          3,
          2,
          1,
          1,
          0,
          3,
          1,
          4,
          1,
          1,
          1,
          2,
          1,
          2
        ],
        [
          6,
          6,
          6,
          8,
          2,
          2,
          8,
          8,
          8,
          4,
          4,
          8,
          0,
          8,
          1,
          8,
          1,
          2,
          1,
          2,
          4,
          2,
          2,
          2,
          1,
          1,
          1,
          3,
          0,
          1,
          2,
          1,
          1,
          2,
          8,
          2
        ],
        [
          2,
          6,
          6,
          6,
          6,
          2,
          8,
          2,
          6,
          2,
          4,
          2,
          2,
          2,
          2,
          2,
          8,
          2,
          2,
          2,
          4,
          2,
          2,
          2,
          1,
          2,
          2,
          3,
          2,
          4,
          1,
          1,
          3,
          3,
          8,
          2
        ],
        [
          1,
          1,
          1,
          6,
          6,
          6,
          6,
          6,
          1,
          1,
          3,
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          8,
          8,
          8,
          4,
          8,
          3,
          2,
          2,
          3,
          3,
          4,
          4,
          2,
          3,
          8,
          3,
          3,
          3
        ],
        [
          2,
          1,
          1,
          8,
          8,
          6,
          6,
          6,
          2,
          3,
          2,
          3,
          3,
          3,
          3,
          2,
          3,
          3,
          2,
          3,
          8,
          4,
          4,
          2,
          3,
          3,
          2,
          3,
          4,
          2,
          2,
          2,
          0,
          8,
          8,
          2
        ],
        [
          2,
          3,
          2,
          8,
          3,
          3,
          2,
          3,
          2,
          3,
          2,
          3,
          3,
          3,
          3,
          2,
          2,
          2,
          2,
          2,
          1,
          2,
          2,
          4,
          3,
          2,
          2,
          4,
          4,
          2,
          2,
          2,
          2,
          8,
          0,
          2
        ]
      ]
    },
    "blocks": [],
    "rocketTargets": null,
    "garage": {
      "col": 0,
      "carriers": [
        {
          "color": 0
        }
      ]
    },
    "carrierLayouts": [
      {
        "name": "new-level-7-hard-v1",
        "difficulty": "hard",
        "grid": [
          [
            {
              "type": "carrier",
              "color": 0
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "wall"
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "carrier",
              "color": 3
            },
            {
              "type": "carrier",
              "color": 1
            }
          ],
          [
            {
              "type": "carrier",
              "color": 4
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "wall"
            },
            null,
            {
              "type": "carrier",
              "color": 8
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 5
            }
          ],
          [
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 3
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 0
            },
            {
              "type": "carrier",
              "color": 1
            }
          ],
          [
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 4
            },
            {
              "type": "carrier",
              "color": 0
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 8
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "wall"
            }
          ],
          [
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "carrier",
              "color": 1
            },
            {
              "type": "wall"
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 8
            },
            {
              "type": "carrier",
              "color": 3
            }
          ],
          [
            {
              "type": "carrier",
              "color": 0
            },
            null,
            {
              "type": "carrier",
              "color": 3
            },
            {
              "type": "wall"
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "carrier",
              "color": 1
            }
          ],
          [
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "wall"
            }
          ]
        ]
      },
      {
        "name": "new-level-7-medium-v1",
        "difficulty": "medium",
        "grid": [
          [
            {
              "type": "wall"
            },
            {
              "type": "wall"
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "carrier",
              "color": 4
            },
            {
              "type": "carrier",
              "color": 3
            },
            null
          ],
          [
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 3
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 0
            }
          ],
          [
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 8
            },
            {
              "type": "carrier",
              "color": 1
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 8
            }
          ],
          [
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "carrier",
              "color": 6
            },
            {
              "type": "carrier",
              "color": 1
            },
            {
              "type": "carrier",
              "color": 3
            },
            null,
            {
              "type": "wall"
            }
          ],
          [
            null,
            {
              "type": "carrier",
              "color": 8
            },
            {
              "type": "carrier",
              "color": 1
            },
            {
              "type": "carrier",
              "color": 0
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "wall"
            }
          ],
          [
            {
              "type": "carrier",
              "color": 4
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "wall"
            },
            {
              "type": "wall"
            },
            {
              "type": "carrier",
              "color": 5
            },
            {
              "type": "carrier",
              "color": 3
            }
          ],
          [
            {
              "type": "carrier",
              "color": 0
            },
            {
              "type": "wall"
            },
            {
              "type": "wall"
            },
            {
              "type": "garage",
              "queue": [
                {
                  "color": 2
                },
                {
                  "color": 0
                }
              ]
            },
            {
              "type": "carrier",
              "color": 1
            },
            {
              "type": "carrier",
              "color": 2
            },
            {
              "type": "carrier",
              "color": 2
            }
          ]
        ]
      }
    ]
  }
];
